name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/rc474o4atfi0eon9hnf64/f0a0d5b9-1a6f-11f1-8aaa-9828a60d55de.zip?rlkey=q2vt8gu8qya8zt73mcjzdiqhr&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project ribcage.xcodeproj -scheme 'ribcage' -archivePath ribcage.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv ribcage.xcarchive/Products/Applications/ribcage.app Payload/ribcage.app

          zip -r "ribcage.ipa" "Payload"

          mv ribcage.ipa ${{ runner.temp }}/ribcage.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: ribcage
          path: ${{ runner.temp }}/ribcage.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3